config/routes.rb
Rails.application.routes.draw do

  resources :given_answers
  get 'students/set_quiz_session'

  resources :given_answers

  #change the sign_in and sign_out routes to /login and /logout
  devise_for :users, path: '', path_names: { sign_in: 'login',
                                             sign_out: 'logout'},
             :controllers => {:registrations => 'registrations'}

  resources :quiz_sessions, :answers, :questions, :quizzes, :courses

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'teacher/quiz_start', to: 'pages#create_session', :as => :teacher_start_quiz
  get 'teacher/quiz_question', to: 'pages#show_question', :as => :teacher_question
  get 'teacher/quiz_question_result', to: 'pages#show_question_result', :as => :teacher_question_result
  get 'teacher/quiz_result', to: 'pages#show_quiz_result', :as => :teacher_quiz_result
  get 'teacher/end_quiz_teacher', to: 'pages#end_quiz_teacher', :as => :end_quiz_teacher
  get 'teacher/new_quiz', to: 'pages#show', :role => 'teacher', :page => 'new_quiz', :as => :new_teacher_quiz
  get 'teacher/new_course', to: 'pages#show', :role => 'teacher', :page => 'new_course', :as => :new_teacher_course
  get 'teacher/home', to: 'pages#show', :role => 'teacher', :page => 'home', :as => :teacher_home
  get 'teacher', to: 'pages#show', :role => 'teacher', :page => 'home'
  get 'teacher/delete_quiz', to: 'quizzes#destroy', :as => :teacher_delete_quiz

  get 'student/quiz_start', to: 'pages#join_session', :as => :student_start_quiz
  get 'student/end_quiz_student', to: 'pages#end_quiz_student', :as => :end_quiz_student
  get 'student/home', to: 'pages#show', :role => 'student', :page => 'home', :as => :student_home
  get 'student', to: 'pages#show', :role => 'student', :page => 'home'

  devise_scope :user do
    get 'teacher_registration/sign_up' => 'devise/registrations#new', :teacher => 'yes'
  end

  get ':role/:page', to: 'pages#show'

  get '/', to: 'pages#show', :as => :welcome_page

  match '*path', to: 'pages#show', via: :all

  mount ActionCable.server => '/cable'
end

app/models/teacher.rb
class Teacher < User

end

app/views/pages/teacher/home.html.erb
<div class="row">
  <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
    <div class="question">
      <div class="jumbotron">
        <h1>Overview Page</h1>
      </div>
      <div><h2>Quizzes</h2></div>
      <ul class="question-info">
        <ul class="courses">
          <%= link_to 'Add Course', new_teacher_course_path, class: 'btn btn-sm btn-default margin-left' %>
          <hr>
          <% if @courses.present? %>
            <%= if @courses.present? then render 'courses_list' end %>
          <% end %>
        </ul>
      </ul>
    </div>
  </div>
</div>

app/views/pages/teacher/new_course.html.erb
<div class="row">
  <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
    <div class="question">
      <div class="jumbotron">
        <h1>Create new course</h1>
      </div>
      <%= simple_form_for Course.new do |f| %>
          <ul class="question-info">
            <ul class="courses">
              </br>
              <div class="form-group">
                <%= f.hidden_field :teacher_id, required: true, class:"form-control", value: current_user.id %>
              </div>
              <div class="form-group">
                <%= f.label :title, 'Course Title' %><br />
                <%= f.text_field :title, required: true, placeholder: 'Enter the course title here', class:"form-control" %>
              </div>
              <div class="form-group">
                <%= f.label :title, 'Semester' %><br />
                <%= f.select :semester, options_for_select([['SS18'], ['WS18'], ['SS19']]), class:"form-control" %>
              </div>
              </br>
            </ul>
          </ul>
          <div class='question-next-button'>
            <%= link_to 'Back', teacher_home_path, :class => 'btn btn-primary btn-lg' %>
            <%= f.button :submit, 'Create Course', :class => 'btn btn-primary btn-lg' %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/teacher/new_quiz.html.erb
<div class="row">
  <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
    <div class="question">
      <div class="jumbotron">
        <h1>Create new quiz</h1>
      </div>
      <%= simple_form_for Quiz.new do |f| %>
      <ul class="question-info">
        <ul class="courses">
          </br>
          <div class="form-group">
            <%= f.hidden_field :course_id, value: params[:course_id] %>
          </div>
          <%= render 'form', :f => f %>
          </br>
        </ul>
      </ul>
      <div class='question-next-button'>
        <%= link_to 'Back', teacher_home_path, class: 'btn btn-primary btn-lg' %>
        <%= f.button :submit, 'Create Quiz', :class => 'btn btn-primary btn-lg' %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/teacher/quiz_question.html.erb
<div class="user-layout">

  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      <div class="question">
        <div class="jumbotron">
          <span class="question-index"><%= @quiz_session.current_question_index+1 %></span>
          <h2><%= @quiz_session.current_question.title%></h2>
        </div>
        <ul class="question-info">
          <li></li>
          <li><span class="badge" id="given_answers_counter">0</span> of <span class="badge" id="students_counter">0</span> participants answered so far.</li>
        </ul>
        <div class="question-next-button">
          <%= link_to 'Next', {:controller => :pages, :action => :show_question_result}, :class => 'btn btn-primary btn-lg', :id => 'question_result_button' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/teacher/quiz_question_result.html.erb
<div class="user-layout">

  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      <div class="question">
        <div class="jumbotron">
          <span class="question-index"><%= @quiz_session.current_question_index+1 %></span>
          <h2><%= @quiz_session.current_question.title%></h2>

        </div>
        <ul class="question-info">
          <%=
            height = current_user.quiz_session.calc_chart_height
            #bar_chart GivenAnswer.where(quiz_session_id: @quiz_session.id, question_id: @quiz_session.current_question.id).group(:answer).count,
            data = current_user.quiz_session.parse_given_answers
            colorArray = current_user.quiz_session.calculate_colors
            bar_chart data,
                        min:0, max: height, width: '100%', colors: colorArray,
                        library: {
                            legend: { position: 'none' },
                            #height: 1000,
                            vAxis: {
                                format: '#',
                                textPosition: 'in',
                                textStyle: {
                                    italic: false,
                                    fontSize: 15
                                }
                            },
                            chartArea: {
                                left: '10%'
                                #height: 150,
                            },
                            bar: {
                                groupWidth: '100%'
                            }
                        }
          %>
          <li><span class="badge"><%= current_user.quiz_session.calc_correct_answer %></span> is correct.</li>
          <li><span class="badge"><%= current_user.quiz_session.calc_correct_answer_count %></span>
            of <span class="badge"><%= current_user.quiz_session.calc_given_answer_count%></span>
            (<%= current_user.quiz_session.calc_answer_percent %>%) Students answered correctly.</br>
          <% if current_user.quiz_session.calc_no_answer_given_count > 0 %>
            <span class="badge"><%= current_user.quiz_session.calc_no_answer_given_count %></span>
            of  <span class="badge"><%= current_user.quiz_session.calc_given_answer_count%></span>
            (<%= current_user.quiz_session.calc_no_answer_given_percent %>%) connected Students did not answer.
          <% end %>
          </li>
        </ul></br>
        <div class="question-next-button">
          <%= link_to 'Next', {:controller => :pages, :action => :show_question}, :class => 'btn btn-primary btn-lg', :id => 'next_quiz_button' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/teacher/quiz_result.html.erb
<div class="user-layout">

  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      <div class="question">
        <div class="jumbotron">
          <span class="question-index"><span class="glyphicon glyphicon-star"></span></span>
          <h2>Quiz Result</h2>
        </div>
        <ul class="question-info">
          <%=
            bar_chart current_user.quiz_session.quiz_result_data,
                      min: 0.0, max: 100.0, colors: [ '#94bace'],
                      library: {
                          vAxis: {
                              format: '#',
                              textPosition: 'in',
                              textStyle: {
                                  italic: false,
                                  fontSize: 15
                              }
                          },
                          hAxis: {
                              ticks: [
                              {v:100,f:'100%'},
                              {v:75,f:'75%'},
                              {v:50,f:'50%'},
                              {v:25,f:'25%'},
                              {v:0,f:'0%'}]
                          },
                          chartArea: {
                              left: '10%'
                          }
                      }
          %>
          <% if current_user.quiz_session.calc_answer_percent_of(current_user.quiz_session.calc_most_diff_question.id) < 75 %>
            <li>Most difficult question: <%= current_user.quiz_session.calc_most_diff_question.title %></li>
          <% end %>
          <li>Top 3 students (based on correct answers and time):</li>
          <% current_user.quiz_session.calc_top_three.each_with_index do |user_info,index| %>
              <li>
                <%= (index+1).to_s + '. ' + user_info[0] + ' (' + user_info[1].to_s + ' correct answers)' %>
              </li>
          <% end %>
          <li></li>
        </ul>
        <div class="question-next-button">
          <%= link_to 'End Quiz', {:controller => :pages, :action => :end_quiz_teacher }, :class => 'btn btn-primary btn-lg', :id => 'end_quiz_button' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/teacher/quiz_start.html.erb
<div class="row">
  <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
    <div class="question">
      <div class="jumbotron">
        <h1>Quiz: <%= @quiz.title %></h1>
        <p>Go to: <code class="dont-break-out">http://gamertests.entertain.univie.ac.at</code><br/><br/>
          Sign up, login and input this access code to participate:
          <code><%= @quiz_session.access_key %></code></p>
      </div>
      <ul class="question-info">
        <li>
          <span class="badge"><%= @quiz.questions.length %></span> questions</li>
        <li><span class="badge" id="students_counter">0</span> participants connected</li>
      </ul>
      <div class="question-next-button" data-no-turbolink>
        <%= link_to 'Start Quiz!', {:controller => :pages, :action => :show_question}, :class => 'btn btn-primary btn-lg', :id => 'start_quiz_button' %>
      </div>
    </div>
  </div>
</div>