config/routes.rb
Rails.application.routes.draw do

  resources :given_answers
  get 'students/set_quiz_session'

  resources :given_answers

  #change the sign_in and sign_out routes to /login and /logout
  devise_for :users, path: '', path_names: { sign_in: 'login',
                                             sign_out: 'logout'},
             :controllers => {:registrations => 'registrations'}

  resources :quiz_sessions, :answers, :questions, :quizzes, :courses

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'teacher/quiz_start', to: 'pages#create_session', :as => :teacher_start_quiz
  get 'teacher/quiz_question', to: 'pages#show_question', :as => :teacher_question
  get 'teacher/quiz_question_result', to: 'pages#show_question_result', :as => :teacher_question_result
  get 'teacher/quiz_result', to: 'pages#show_quiz_result', :as => :teacher_quiz_result
  get 'teacher/end_quiz_teacher', to: 'pages#end_quiz_teacher', :as => :end_quiz_teacher
  get 'teacher/new_quiz', to: 'pages#show', :role => 'teacher', :page => 'new_quiz', :as => :new_teacher_quiz
  get 'teacher/new_course', to: 'pages#show', :role => 'teacher', :page => 'new_course', :as => :new_teacher_course
  get 'teacher/home', to: 'pages#show', :role => 'teacher', :page => 'home', :as => :teacher_home
  get 'teacher', to: 'pages#show', :role => 'teacher', :page => 'home'
  get 'teacher/delete_quiz', to: 'quizzes#destroy', :as => :teacher_delete_quiz

  get 'student/quiz_start', to: 'pages#join_session', :as => :student_start_quiz
  get 'student/end_quiz_student', to: 'pages#end_quiz_student', :as => :end_quiz_student
  get 'student/home', to: 'pages#show', :role => 'student', :page => 'home', :as => :student_home
  get 'student', to: 'pages#show', :role => 'student', :page => 'home'

  devise_scope :user do
    get 'teacher_registration/sign_up' => 'devise/registrations#new', :teacher => 'yes'
  end

  get ':role/:page', to: 'pages#show'

  get '/', to: 'pages#show', :as => :welcome_page

  match '*path', to: 'pages#show', via: :all

  mount ActionCable.server => '/cable'
end

app/models/given_answer.rb
class GivenAnswer < ApplicationRecord
  belongs_to :student
  belongs_to :quiz_session
  belongs_to :question
end

app/controllers/given_answers_controller.rb
class GivenAnswersController < ApplicationController
  before_action :set_given_answer, only: [:show, :edit, :update, :destroy]

  # GET /given_answers
  # GET /given_answers.json
  def index
    @given_answers = GivenAnswer.all
  end

  # GET /given_answers/1
  # GET /given_answers/1.json
  def show
  end

  # GET /given_answers/new
  def new
    @given_answer = GivenAnswer.new
  end

  # GET /given_answers/1/edit
  def edit
  end

  # POST /given_answers
  # POST /given_answers.json
  def create
    @given_answer = GivenAnswer.new(given_answer_params)

    respond_to do |format|
      if @given_answer.save
        format.html { redirect_to @given_answer, notice: 'Given answer was successfully created.' }
        format.json { render :show, status: :created, location: @given_answer }
      else
        format.html { render :new }
        format.json { render json: @given_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /given_answers/1
  # PATCH/PUT /given_answers/1.json
  def update
    respond_to do |format|
      if @given_answer.update(given_answer_params)
        format.html { redirect_to @given_answer, notice: 'Given answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @given_answer }
      else
        format.html { render :edit }
        format.json { render json: @given_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /given_answers/1
  # DELETE /given_answers/1.json
  def destroy
    @given_answer.destroy
    respond_to do |format|
      format.html { redirect_to given_answers_url, notice: 'Given answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_given_answer
      @given_answer = GivenAnswer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def given_answer_params
      params.require(:given_answer).permit(:student_id, :quiz_session_id, :question_id, :answer, :correct)
    end
end

app/helpers/given_answers_helper.rb
module GivenAnswersHelper
end

app/views/given_answers/_form.html.erb
<%= simple_form_for(@given_answer) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :student %>
    <%= f.association :quiz_session %>
    <%= f.association :question %>
    <%= f.input :answer %>
    <%= f.input :correct %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/given_answers/edit.html.erb
<h1>Editing Given Answer</h1>

<%= render 'form', given_answer: @given_answer %>

<%= link_to 'Show', @given_answer %> |
<%= link_to 'Back', given_answers_path %>

app/views/given_answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Given Answers</h1>

<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>Quiz session</th>
      <th>Question</th>
      <th>Answer</th>
      <th>Correct</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @given_answers.each do |given_answer| %>
      <tr>
        <td><%= given_answer.student %></td>
        <td><%= given_answer.quiz_session %></td>
        <td><%= given_answer.question %></td>
        <td><%= given_answer.answer %></td>
        <td><%= given_answer.correct %></td>
        <td><%= link_to 'Show', given_answer %></td>
        <td><%= link_to 'Edit', edit_given_answer_path(given_answer) %></td>
        <td><%= link_to 'Destroy', given_answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Given Answer', new_given_answer_path %>

app/views/given_answers/new.html.erb
<h1>New Given Answer</h1>

<%= render 'form', given_answer: @given_answer %>

<%= link_to 'Back', given_answers_path %>

app/views/given_answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @given_answer.student %>
</p>

<p>
  <strong>Quiz session:</strong>
  <%= @given_answer.quiz_session %>
</p>

<p>
  <strong>Question:</strong>
  <%= @given_answer.question %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @given_answer.answer %>
</p>

<p>
  <strong>Correct:</strong>
  <%= @given_answer.correct %>
</p>

<%= link_to 'Edit', edit_given_answer_path(@given_answer) %> |
<%= link_to 'Back', given_answers_path %>