config/routes.rb
Rails.application.routes.draw do

  resources :given_answers
  get 'students/set_quiz_session'

  resources :given_answers

  #change the sign_in and sign_out routes to /login and /logout
  devise_for :users, path: '', path_names: { sign_in: 'login',
                                             sign_out: 'logout'},
             :controllers => {:registrations => 'registrations'}

  resources :quiz_sessions, :answers, :questions, :quizzes, :courses

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'teacher/quiz_start', to: 'pages#create_session', :as => :teacher_start_quiz
  get 'teacher/quiz_question', to: 'pages#show_question', :as => :teacher_question
  get 'teacher/quiz_question_result', to: 'pages#show_question_result', :as => :teacher_question_result
  get 'teacher/quiz_result', to: 'pages#show_quiz_result', :as => :teacher_quiz_result
  get 'teacher/end_quiz_teacher', to: 'pages#end_quiz_teacher', :as => :end_quiz_teacher
  get 'teacher/new_quiz', to: 'pages#show', :role => 'teacher', :page => 'new_quiz', :as => :new_teacher_quiz
  get 'teacher/new_course', to: 'pages#show', :role => 'teacher', :page => 'new_course', :as => :new_teacher_course
  get 'teacher/home', to: 'pages#show', :role => 'teacher', :page => 'home', :as => :teacher_home
  get 'teacher', to: 'pages#show', :role => 'teacher', :page => 'home'
  get 'teacher/delete_quiz', to: 'quizzes#destroy', :as => :teacher_delete_quiz

  get 'student/quiz_start', to: 'pages#join_session', :as => :student_start_quiz
  get 'student/end_quiz_student', to: 'pages#end_quiz_student', :as => :end_quiz_student
  get 'student/home', to: 'pages#show', :role => 'student', :page => 'home', :as => :student_home
  get 'student', to: 'pages#show', :role => 'student', :page => 'home'

  devise_scope :user do
    get 'teacher_registration/sign_up' => 'devise/registrations#new', :teacher => 'yes'
  end

  get ':role/:page', to: 'pages#show'

  get '/', to: 'pages#show', :as => :welcome_page

  match '*path', to: 'pages#show', via: :all

  mount ActionCable.server => '/cable'
end

app/views/pages/_answer_fields.html.erb
<div class="panel panel-default nested-fields answer-container">
  <div class="panel-body">
    <div class="form-group">
      <%= f.label :title, 'Answer' %><br />
      <%= f.text_field :title, required: true, placeholder: 'Enter answer here', class:'form-control' %>
    </div>
    <div class="checkbox">
      <label>
        <%= f.check_box :correct %>
        <%= f.label :correct %>
      </label>
    </div>
    <p>
      <%= link_to_remove_association raw('<i class="fa fa-trash"></i> Remove answer'), f, :class => 'btn btn-sm btn-default' %>
    </p>
  </div>
</div>

app/views/pages/_courses_list.html.erb
<% @courses.each do |course| %>
    <table>
      <thead>
        <tr>
          <th><h3><%= course.title %> (<%=course.semester%>) -&nbsp;</h3></th>
          <th></th>
          <th colspan="3" class="custom-font-20"><h3><%= link_to 'Add Quiz', new_teacher_quiz_path(:course_id => course.id) %></h3></th>
        </tr>
      </thead>
      <tbody>
        <tr><td>&nbsp;&nbsp;</td></tr>
        <% course.quizzes.each do |quiz| %>
          <tr>
            <td class="custom-font-20"><p><%= quiz.title %></p></td>
            <td>&nbsp;&nbsp;</td>
            <% if current_user.quiz_session.present? %>
              <% if quiz.id == QuizSession.find(current_user.quiz_session.id).quiz_id  %>
                <div><td class="custom-font-20"><%= link_to 'Continue', page: 'quiz_start', :quiz => quiz.id %></td></div>
                <div><td class="custom-font-20">&nbsp;|&nbsp;</td></div>
                <div><td class="custom-font-20"><%= link_to raw('<i class="fa fa-times">'), end_quiz_teacher_path %></td></div>
              <% else %>
                <div><td></td></div>
              <% end %>
            <% else %>
                <div><td class="custom-font-20"><%= link_to 'Start Quiz', page: 'quiz_start', :quiz => quiz.id %></td></div>
                <div><td class="custom-font-20">&nbsp;|&nbsp;</td></div>
                <div><td class="custom-font-20"><%= link_to raw('<i class="fa fa-trash">'), teacher_delete_quiz_path(:id => quiz.id), :data => { :confirm => 'Are you sure you want to delete this quiz?' } %></td></div>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
<% end %>

app/views/pages/_form.html.erb
<div class="form-group">
  <%= f.label :title, 'Quiz Title' %><br />
  <%= f.text_field :title, required: true, placeholder: 'Enter the quiz title here', class:"form-control" %>
</div>

<%= f.fields_for :questions do |question| %>
    <%= render 'question_fields', :f => question %>
<% end %>

<p>
  <%= link_to_add_association raw('<i class="fa fa-plus"></i> Add a question'), f,
                              :questions, :class => 'btn btn-sm btn-default',
                              :partial => 'question_fields' %>
</p>

app/views/pages/_question_fields.html.erb
<div class="panel panel-default nested-fields question-container">
  <div class="panel-body">
    <div class="form-group">
      <%= f.label :title, 'Question' %><br />
      <%= f.text_field :title, required: true, placeholder: 'Enter the question here', class: 'form-control' %>
    </div>
    <br />
    <%= f.fields_for :answers do |answer| %>
        <%= render 'answer_fields', :f => answer %>
    <% end %>
    <p>
      <%= link_to_add_association raw('<i class="fa fa-plus"></i> Add an answer'), f,
                                :answers, :class => 'btn btn-sm btn-default',
                                :partial => 'answer_fields' %>
      <%= link_to_remove_association raw('<i class="fa fa-trash"></i> Remove question'), f, :class => 'btn btn-sm btn-default' %>
    </p>
  </div>
</div>

app/views/pages/_test.html.erb
<p>test</p>

app/views/pages/welcome.html.erb
<div class="row">
  <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
    <div class="question">
      <div class="jumbotron">
        <table>
          <tr>
            <td style="width:100%">
              <h1>Lective</h1>
              <h2>Welcome to Lective</h2>
              <br/>
              <ul>
                <p>
                <li>
                  <% if request.fullpath != '/sign_up'  %>
                      <%= link_to "Sign up", new_user_registration_path %>
                  <% end %>
                </li>
                <li>
                  <% if request.fullpath != '/login' %>
                      <%= link_to "Log in", new_user_session_path %>
                  <% end %>
                </li>
                </p>
              </ul>
            </td>
            <td align="right">
              <%= image_tag("hipster2x.png", :size => "300", :alt => "welcome image")%>
            </td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>