config/routes.rb
Rails.application.routes.draw do

  resources :given_answers
  get 'students/set_quiz_session'

  resources :given_answers

  #change the sign_in and sign_out routes to /login and /logout
  devise_for :users, path: '', path_names: { sign_in: 'login',
                                             sign_out: 'logout'},
             :controllers => {:registrations => 'registrations'}

  resources :quiz_sessions, :answers, :questions, :quizzes, :courses

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'teacher/quiz_start', to: 'pages#create_session', :as => :teacher_start_quiz
  get 'teacher/quiz_question', to: 'pages#show_question', :as => :teacher_question
  get 'teacher/quiz_question_result', to: 'pages#show_question_result', :as => :teacher_question_result
  get 'teacher/quiz_result', to: 'pages#show_quiz_result', :as => :teacher_quiz_result
  get 'teacher/end_quiz_teacher', to: 'pages#end_quiz_teacher', :as => :end_quiz_teacher
  get 'teacher/new_quiz', to: 'pages#show', :role => 'teacher', :page => 'new_quiz', :as => :new_teacher_quiz
  get 'teacher/new_course', to: 'pages#show', :role => 'teacher', :page => 'new_course', :as => :new_teacher_course
  get 'teacher/home', to: 'pages#show', :role => 'teacher', :page => 'home', :as => :teacher_home
  get 'teacher', to: 'pages#show', :role => 'teacher', :page => 'home'
  get 'teacher/delete_quiz', to: 'quizzes#destroy', :as => :teacher_delete_quiz

  get 'student/quiz_start', to: 'pages#join_session', :as => :student_start_quiz
  get 'student/end_quiz_student', to: 'pages#end_quiz_student', :as => :end_quiz_student
  get 'student/home', to: 'pages#show', :role => 'student', :page => 'home', :as => :student_home
  get 'student', to: 'pages#show', :role => 'student', :page => 'home'

  devise_scope :user do
    get 'teacher_registration/sign_up' => 'devise/registrations#new', :teacher => 'yes'
  end

  get ':role/:page', to: 'pages#show'

  get '/', to: 'pages#show', :as => :welcome_page

  match '*path', to: 'pages#show', via: :all

  mount ActionCable.server => '/cable'
end

app/models/student.rb
class Student < User
  has_many :given_answers

  #def set_quiz_session(access_key)
  #  access_key = access_key
  #  unless  (access_key =~ /^\h{8}$/)
  #    logger.debug "@access_key: #{access_key}"
  #    raise "Must be a valid access key."
  #  else
  #    self.quiz_session_id = (QuizSession.find_by access_key: access_key).id
  #    if self.save!
  #      #make and save a GivenAnswer record for each question of the current quiz
  #      quiz_session = QuizSession.find(self.quiz_session.id)
  #     questions = Quiz.find(quiz_session.quiz.id).questions

  #      questions.each do |question|
  #        #creates a GivenAnswer object with db default values (correct = false, answer = "[No Answer given.]")
  #        answer = GivenAnswer.where(student_id: self.id, quiz_session_id: quiz_session.id, question_id: question.id).last
  #        if !answer.blank?
  #          answer.update_attributes(answer: "[No answer given]", correct: false)
  #        else
  #          GivenAnswer.create!(student_id: self.id, quiz_session_id: quiz_session.id, question_id: question.id)
  #        end
  #      end
  #    else raise "Quiz session cannot be joined."
  #    end
  #  end
  #end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/pages/student/_answer_option.html.erb
<button class="btn btn-lg btn-default"><%= answer.title %></button>

app/views/pages/student/_quiz_question.html.erb
<div class="student-layout">

  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      <div class="question">
        <div class="jumbotron">
          <h2><!-- @quiz_session.current_question_index -->1. Question</h2>
        </div>
        <div class="question-answers btn-group-vertical" role="group" id="answer-buttons">
          <!-- #append action cable received answer buttons here -->
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/student/home.html.erb
<% if current_user.quiz_session.present? %>
  <h2>Quiz: <%= current_user.quiz_session.quiz.title %></h2>
    <%= link_to 'Reconnect', student_start_quiz_path, :class => 'custom-font-20', :id => 'reconnect_student_button' %>
<% else %>
  <h2>Join Quiz</h2>
  <%= form_tag student_start_quiz_path, :method => 'get' do %>
    <p>
      Enter Access Key: </br>
      <%= text_field_tag :access_key, params[:access_key] %>
      <%= submit_tag 'Go', :name => nil %>
    </p>
  <% end %>
<% end %>

app/views/pages/student/quiz_start.html.erb
<div class="page-content-wrapper container-fluid">

  <div class="row-fluid">
    <div class="col-md-12">
      <h2> Quiz: <%= @quiz.title %></h2>
      <div>
        <%= @quiz.questions.length %> Questions <br/>
      </div>
      <div>
        <p>
          </br>
          </br>
          Quiz will start soon.
        </p>
      </div>
      <div>
        <span class="badge" id="students_counter">0</span> participants connected.
      </div>
      <div>
        </br>
        <div>
          <%= link_to 'Leave Quiz', end_quiz_student_path, class: 'btn btn-sm btn-default', style: 'float: right' %>
        </div>
      </div>
    </div>
  </div>
</div>